BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS region (  id INTEGER PRIMARY KEY,  name TEXT,  translations_json TEXT,  wiki_data_id TEXT);
INSERT INTO region (id, name, translations_json, wiki_data_id) VALUES (1, 'Africa', '{"ko": "아프리카", "pt-BR": "África", "pt": "África", "nl": "Afrika", "hr": "Afrika", "fa": "آفریقا", "de": "Afrika", "es": "África", "fr": "Afrique", "ja": "アフリカ", "it": "Africa", "zh-CN": "非洲", "tr": "Afrika", "ru": "Африка", "uk": "Африка", "pl": "Afryka"}', 'Q15');
INSERT INTO region (id, name, translations_json, wiki_data_id) VALUES (2, 'Americas', '{"ko": "아메리카", "pt-BR": "América", "pt": "América", "nl": "Amerika", "hr": "Amerika", "fa": "قاره آمریکا", "de": "Amerika", "es": "América", "fr": "Amérique", "ja": "アメリカ州", "it": "America", "zh-CN": "美洲", "tr": "Amerika", "ru": "Америка", "uk": "Америка", "pl": "Ameryka"}', 'Q828');
INSERT INTO region (id, name, translations_json, wiki_data_id) VALUES (3, 'Asia', '{"ko": "아시아", "pt-BR": "Ásia", "pt": "Ásia", "nl": "Azië", "hr": "Ázsia", "fa": "آسیا", "de": "Asien", "es": "Asia", "fr": "Asie", "ja": "アジア", "it": "Asia", "zh-CN": "亚洲", "tr": "Asya", "ru": "Азия", "uk": "Азія", "pl": "Azja"}', 'Q48');
INSERT INTO region (id, name, translations_json, wiki_data_id) VALUES (4, 'Europe', '{"ko": "유럽", "pt-BR": "Europa", "pt": "Europa", "nl": "Europa", "hr": "Európa", "fa": "اروپا", "de": "Europa", "es": "Europa", "fr": "Europe", "ja": "ヨーロッパ", "it": "Europa", "zh-CN": "欧洲", "tr": "Avrupa", "ru": "Европа", "uk": "Європа", "pl": "Europa"}', 'Q46');
INSERT INTO region (id, name, translations_json, wiki_data_id) VALUES (5, 'Oceania', '{"ko": "오세아니아", "pt-BR": "Oceania", "pt": "Oceania", "nl": "Oceanië en Australië", "hr": "Óceánia és Ausztrália", "fa": "اقیانوسیه", "de": "Ozeanien und Australien", "es": "Oceanía", "fr": "Océanie", "ja": "オセアニア", "it": "Oceania", "zh-CN": "大洋洲", "tr": "Okyanusya", "ru": "Океания", "uk": "Океанія", "pl": "Oceania"}', 'Q55643');
INSERT INTO region (id, name, translations_json, wiki_data_id) VALUES (6, 'Polar', '{"ko": "남극", "pt-BR": "Antártida", "pt": "Antártida", "nl": "Antarctica", "hr": "Antarktika", "fa": "جنوبگان", "de": "Antarktika", "es": "Antártida", "fr": "Antarctique", "ja": "南極大陸", "it": "Antartide", "zh-CN": "南極洲", "tr": "Antarktika", "ru": "Антарктика", "uk": "Антарктика", "pl": "Antarktyka"}', 'Q51');
COMMIT;
