name: persistence_preferences
description: Account session and preference persistence via SharedPreferences.
publish_to: none

environment:
  sdk: ">=3.11.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  repository_interface_account:
    git:
      url: http://192.168.0.165:3000/xuan/repository-interface-account.git
  shared_preferences: ^2.3.2
  repository_interface_meihuayishu:
    git:
      url: http://192.168.0.165:3000/xuan/repository-interface-meihuayishu.git
  repository_interface_taiyishenshu:
    git:
      url: http://192.168.0.165:3000/xuan/repository-interface-taiyishenshu.git
  repository_interface_bazi:
    git:
      url: http://192.168.0.165:3000/xuan/repository-interface-bazi.git
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
