CREATE TABLE IF NOT EXISTS star_position_status (  id INTEGER PRIMARY KEY,  class_name TEXT,  star TEXT,  position_status_type TEXT,  position_list_json TEXT);
DELETE FROM star_position_status;
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (1, '果老', '日', '庙', '["戌"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (2, '果老', '月', '庙', '["戌"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (3, '果老', '土', '庙', '["丑"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (4, '果老', '罗', '庙', '["寅", "午"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (5, '果老', '火', '庙', '["卯"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (6, '果老', '金', '庙', '["辰"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (7, '果老', '计', '庙', '["巳", "亥"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (8, '果老', '木', '庙', '["亥"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (9, '果老', '水', '庙', '["午"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (10, '果老', '孛', '庙', '["未"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (11, '果老', '炁', '庙', '["申"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (12, '果老', '土', '旺', '["卯"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (13, '果老', '火', '旺', '["丑"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (14, '果老', '金', '旺', '["午", "亥"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (15, '果老', '水', '旺', '["子", "巳"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (16, '果老', '木', '旺', '["未", "亥"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (17, '果老', '日', '旺', '["巳"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (18, '果老', '月', '旺', '["酉"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (19, '果老', '罗', '旺', '["卯"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (20, '果老', '计', '旺', '["卯", "戌"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (21, '果老', '孛', '旺', '["寅"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (22, '果老', '炁', '旺', '["亥"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (23, '果老', '土', '乐', '["子", "丑"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (24, '果老', '火', '乐', '["卯", "戌"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (25, '果老', '金', '乐', '["辰", "酉"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (26, '果老', '水', '乐', '["申", "巳"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (27, '果老', '木', '乐', '["寅", "亥"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (28, '果老', '日', '乐', '["午"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (29, '果老', '月', '乐', '["未"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (30, '果老', '罗', '乐', '["午"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (31, '果老', '计', '乐', '["子"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (32, '果老', '孛', '乐', '["辰"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (33, '果老', '炁', '乐', '["戌"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (34, '果老', '土', '喜', '["午"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (35, '果老', '火', '喜', '["申"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (36, '果老', '水', '喜', '["辰"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (37, '果老', '木', '喜', '["未"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (38, '果老', '日', '喜', '["寅"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (39, '果老', '月', '喜', '["亥"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (40, '果老', '罗', '喜', '["戌"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (41, '果老', '孛', '喜', '["辰"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (42, '星学大成', '土', '正', '["丑"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (43, '星学大成', '土', '偏', '["子"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (44, '星学大成', '木', '正', '["亥"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (45, '星学大成', '木', '偏', '["寅"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (46, '星学大成', '火', '正', '["卯"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (47, '星学大成', '火', '偏', '["戌"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (48, '星学大成', '金', '正', '["辰"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (49, '星学大成', '金', '偏', '["酉"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (50, '星学大成', '水', '正', '["巳"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (51, '星学大成', '水', '偏', '["申"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (52, '果老', '日', '正', '["午"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (53, '果老', '月', '正', '["未"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (54, '果老', '土', '怒', '["巳"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (55, '果老', '火', '怒', '["酉"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (56, '果老', '木', '怒', '["子"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (57, '果老', '水', '怒', '["戌"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (58, '果老', '金', '怒', '["寅"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (59, '果老', '土', '殿', '["柳", "女", "胃", "氐"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (60, '果老', '木', '殿', '["奎", "角", "斗", "井"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (61, '果老', '火', '殿', '["翼", "尾", "室", "觜"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (62, '果老', '金', '殿', '["牛", "亢", "娄", "鬼"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (63, '果老', '水', '殿', '["箕", "轸", "参", "壁"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (64, '果老', '日', '殿', '["虚", "房", "昴", "星"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (65, '果老', '月', '殿', '["毕", "危", "张", "心"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (66, '果老', '土', '凶', '["巳"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (67, '果老', '火', '凶', '["酉"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (68, '果老', '金', '凶', '["卯"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (69, '果老', '水', '凶', '["戌"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (70, '果老', '日', '凶', '["子"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (71, '果老', '罗', '凶', '["子"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (72, '果老', '计', '凶', '["亥"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (73, '果老', '土', '贵', '["斗"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (74, '果老', '火', '贵', '["心"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (75, '果老', '火', '贵', '["氐"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (76, '果老', '火', '贵', '["角"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (77, '果老', '火', '贵', '["斗"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (78, '果老', '火', '贵', '["娄"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (79, '果老', '金', '贵', '["箕"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (80, '果老', '金', '贵', '["胃"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (81, '果老', '木', '贵', '["参"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (82, '果老', '日', '贵', '["奎"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (83, '果老', '水', '贵', '["星"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (84, '果老', '月', '贵', '["牛"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (85, '果老', '月', '贵', '["鬼"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (86, '果老', '炁', '贵', '["觜"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (87, '果老', '炁', '贵', '["角", "亢"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (88, '果老', '炁', '贵', '["斗"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (89, '果老', '罗', '贵', '["房"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (90, '果老', '罗', '贵', '["卯"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (91, '果老', '罗', '贵', '["张"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (92, '果老', '计', '贵', '["箕"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (93, '果老', '计', '贵', '["危"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (94, '果老', '计', '贵', '["奎"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (95, '果老', '计', '贵', '["胃"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (96, '果老', '孛', '贵', '["井"]');
INSERT INTO star_position_status ("id", "class_name", "star", "position_status_type", "position_list_json") VALUES (97, '果老', '计', '贵', '["柳"]');
